### ISSUE TITLE
What do in the pub/sub system if elastic wouldn't be accesible?

### ISSUE THREAD

**Issue by gabrieltholsgard** [projectcs13/sensor-cloud#179]
I was wondering especially for virtual streams what will happen when it have calculated a new value, but cannot store it into ES because of crash or some other error. Some options:
1. Terminate the virtual stream process, i.e restarting it
2. Don't store it, but publish it into Rabbit MQ and wait for new values
3. Don't do anything just wait for new values

I'm thinking of option 2, but need some input please

**Comment by andreasmh** [comment]
Well, the problem with only giving it to rabbitMQ is that it will not appear in the history of the virtual stream. This can cause inconsistencies. I would probably say option 3 for lazyness sake. Otherwise you should make sure some way that the value is logged and can be indexed later, in that case go with option 2

**Comment by gxlzlihao** [comment]
Since the new values may come after this value, I don`t think it is a good idea to restart the system. I think to publish this value to the webpages and give some feedback to users at the same time would be much better. Or if possible store this value in some log, and try to put it into elasticsearch later. How do the other guys think?

**Comment by nikokon** [comment]
I would go with putting it in a log...

**Comment by gabrieltholsgard** [comment]
Hmm... okay so having a log which is fairly easy to do would mean then that as soon as I can store a value I will also store all values that are in the log.. but I would still publish the values as they come in, unless they can't be published as well that is :)

**Comment by gabrieltholsgard** [comment]
And follow up question to having a log
Should the log be discarded when the process terminates, normally or abnormally?

**Comment by gabrieltholsgard** [comment]
I will do a log, and I think I will just discard if it crashes... for now at least
