### ISSUE TITLE
are predictions virtual streams yet?

### ISSUE THREAD

**Issue by konstantino** [projectcs13/sensor-cloud#217]
rekindling an older discussion here - I was wondering if predictions (predictive streams) are available as virtual streams and if so how does that work?

**Comment by iakovosk** [comment]
Predictions in virtual streams are supported in the same way as in ordinary streams: The user just clciks "Fetch predictions" and will get some values which will not be stored.

**Comment by konstantino** [comment]
so how does one subscribe to such a stream from the API?

**Comment by iakovosk** [comment]
It turns out I misunderstood the question. Predictions work as follows: for a given input, i.e. some values, there is a fixed amount of predicted values coming out. No more will be created over time. And then, if the input changes(more values are stores) and we ask for predictions again, these predictions will be created from scratch and will be very different than the previous ones. So, we did not really see a point in creating a virtual stream to store/include them.

**Comment by konstantino** [comment]
yes but without having predictions as virtual streams the predictive
information cannot be re-used - it is just visualised. my interest is to
make this available as a service via an API.

**Comment by konstantino** [comment]
another possibility here - if we want to avoid predictive virtual streams (which will ultimately change all the time when a new value is put into the system) - then we can think of an export function in the gui (or via the API) that would just provide a dump of the current predicted data points - that would also allow for re-using the computation already made by the engine. what do you think?

**Comment by steine** [comment]
Right now you can get the predicted data by doing a curl GET to /streams/ID/_analyse?nr_values=X&nr_preds=Y
X defaults to 50
Y defaults to 25

**Comment by konstantino** [comment]
good. then this enough.
