### ISSUE TITLE
Cannot install system on Ubuntu 14.04

### ISSUE THREAD

**Issue by piffy** [projectcs13/sensor-cloud#250]
## Installation problem

I wanted to try out your system, and I'm totally clueless about Erlang. So I followed your instructions and typed the  "make install_linux_deps" on a (almost new) Ubuntu 14.04
It gave a dependency error: 

 r-base : Depends: r-base-core (>= 3.1.0-1precise0) but it is not going to be installed
          Dipende: r-recommended (= 3.1.0-1precise0) but it is not going to be installed
          Reccommends: r-base-html but it is not going to be installed

**Comment by konstantino** [comment]
Apparently there is something odd with Ubuntu 14.04 which has not caught my attention yet since I mostly use 12.04LTS 64 bit (as mentioned here https://github.com/projectcs13/sensor-cloud/wiki/Setup) when setting up new instances of this system. However, your problem seems to be limited to R and has not much to do with Erlang. Have you tried the install.sh script which you can find in the scripts directory? (https://github.com/projectcs13/sensor-cloud/blob/develop/scripts/install.sh) 

There is a very specific segment there that adds a particular repository for R which should help you go around this problem.

**Comment by piffy** [comment]
I found the solution. In effects, there should be something wrong with the new repos in trusty 
I had to add this line to /etc/apt/sources.list

deb http://cran.r-project.org/bin/linux/ubuntu/ trusty/

and then manually add the key via 
 sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

(maybe you should add it to the docs: )
